name: dog_breed
channels:
  - nodefaults
  - anaconda
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.8.4
  - numpy=1.23.4
  - opencv=4.6.0
  - pandas=2.2.2
  - python=3.9.20
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - streamlit=1.37.1
  - tensorflow-gpu=2.4.1
  - tqdm=4.66.5
