name: dog_breed
channels:
  - anaconda
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - opencv=4.10.0
  - pandas=2.2.2
  - python=3.12.7
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - streamlit=1.37.1
  - tensorflow=2.17.0
